{
    "testsuites": {
        "testsuite": {
            "@name": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot-20230110104511",
            "@tests": "1",
            "@file": "validation_framework/validators/tests/nuvla_operations/test_engine_reboot.py",
            "@time": "0.001",
            "@timestamp": "2023-01-10T10:45:11",
            "@failures": "0",
            "@errors": "1",
            "@skipped": "0",
            "testcase": {
                "@classname": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot",
                "@name": "test_engine_reboot",
                "@time": "0.001",
                "error": {
                    "@type": "FileNotFoundError",
                    "@message": "Provided file /Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/conf/targets/rpi4.toml does not exists",
                    "#text": "Traceback (most recent call last):\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/validators/validation_base.py\", line 143, in setUp\n    self.engine_handler: EngineHandler = EngineHandler(cte.DEVICE_CONFIG_PATH / self.target_config_file,\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/engine_handler.py\", line 42, in __init__\n    raise FileNotFoundError(f'Provided file {self.device_config_file} does not exists')\nFileNotFoundError: Provided file /Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/conf/targets/rpi4.toml does not exists"
                }
            }
        }
    },
    "target_device": "rpi4.toml",
    "test_type": "nuvla_operations"
}