{
    "testsuites": {
        "testsuite": {
            "@name": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot-20221213085726",
            "@tests": "1",
            "@file": "validation_framework/validators/tests/nuvla_operations/test_engine_reboot.py",
            "@time": "201.982",
            "@timestamp": "2022-12-13T09:00:48",
            "@failures": "0",
            "@errors": "1",
            "@skipped": "0",
            "testcase": {
                "@classname": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot",
                "@name": "test_engine_reboot",
                "@time": "201.982",
                "error": {
                    "@type": "ConnectionResetError",
                    "@message": "[Errno 54] Connection reset by peer",
                    "#text": "Traceback (most recent call last):\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/validators/tests/nuvla_operations/test_engine_reboot.py\", line 75, in test_engine_reboot\n    while self.engine_handler.device.is_reachable(silent=True):\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/target_device/ssh_target.py\", line 52, in is_reachable\n    it_result: fabric.Result = self.run_command('hostname')\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/target_device/ssh_target.py\", line 88, in run_command\n    return connection.run(command, env=envs, hide=True)\n  File \"<decorator-gen-3>\", line 2, in run\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 30, in opens\n    return method(self, *args, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 725, in run\n    return self._run(self._remote_runner(), command, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/invoke/context.py\", line 102, in _run\n    return runner.run(command, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/runners.py\", line 72, in run\n    return super(Remote, self).run(command, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/invoke/runners.py\", line 380, in run\n    return self._run_body(command, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/invoke/runners.py\", line 431, in _run_body\n    self.start(command, self.opts[\"shell\"], self.env)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/runners.py\", line 38, in start\n    self.channel = self.context.create_session()\n  File \"<decorator-gen-2>\", line 2, in create_session\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 30, in opens\n    return method(self, *args, **kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 700, in create_session\n    channel = self.transport.open_session()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/transport.py\", line 920, in open_session\n    return self.open_channel(\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/transport.py\", line 1051, in open_channel\n    raise e\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/transport.py\", line 2110, in run\n    ptype, m = self.packetizer.read_message()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/packet.py\", line 459, in read_message\n    header = self.read_all(self.__block_size_in, check_rekey=True)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/packet.py\", line 301, in read_all\n    x = self.__socket.recv(n)\nConnectionResetError: [Errno 54] Connection reset by peer"
                },
                "system-out": "~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml\nnohup docker-compose -p NuvlaEdge_Validator -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml up -d\n{'location': 'job/dde26ddb-32eb-46b7-b5d2-5553fde63b10',\n 'message': 'sending reboot request to NuvlaBox '\n            'nuvlabox/48a2dde6-a3ea-4a20-a449-33a01d39dec4 with async '\n            'job/dde26ddb-32eb-46b7-b5d2-5553fde63b10',\n 'resource-id': 'nuvlabox/48a2dde6-a3ea-4a20-a449-33a01d39dec4',\n 'status': 202}"
            }
        }
    },
    "target_device": "rpi4.toml"
}