{
    "testsuites": {
        "testsuite": {
            "@name": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot-20221212180238",
            "@tests": "2",
            "@file": "validation_framework/validators/tests/nuvla_operations/test_engine_reboot.py",
            "@time": "453.006",
            "@timestamp": "2022-12-12T18:10:11",
            "@failures": "0",
            "@errors": "2",
            "@skipped": "0",
            "testcase": [
                {
                    "@classname": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot",
                    "@name": "test_engine_reboot",
                    "@time": "0.000",
                    "error": {
                        "@type": "TimeoutError",
                        "@message": "timed out",
                        "#text": "Traceback (most recent call last):\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/validators/tests/nuvla_operations/test_engine_reboot.py\", line 72, in test_engine_reboot\n    response: Result = self.engine_handler.device.run_command(\"awk '{print $1}' /proc/uptime\")\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/target_device/ssh_target.py\", line 86, in run_command\n    return connection.run(command, env=envs, hide=True)\n  File \"<decorator-gen-3>\", line 2, in run\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 29, in opens\n    self.open()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 636, in open\n    self.client.connect(**kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/client.py\", line 358, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/util.py\", line 279, in retry_on_signal\n    return function()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/client.py\", line 358, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\nTimeoutError: timed out"
                    },
                    "system-out": "~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml\nnohup docker-compose -p NuvlaEdge_Validator -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml up -d\n{'location': 'job/a0dce27e-ac36-4c95-aa81-86357d09a475',\n 'message': 'sending reboot request to NuvlaBox '\n            'nuvlabox/3a8f2283-8033-4a3c-8b07-ae3168d67ae6 with async '\n            'job/a0dce27e-ac36-4c95-aa81-86357d09a475',\n 'resource-id': 'nuvlabox/3a8f2283-8033-4a3c-8b07-ae3168d67ae6',\n 'status': 202}"
                },
                {
                    "@classname": "validation_framework.validators.tests.nuvla_operations.test_engine_reboot.TestEngineReboot",
                    "@name": "test_engine_reboot",
                    "@time": "453.006",
                    "error": {
                        "@type": "TimeoutError",
                        "@message": "timed out",
                        "#text": "Traceback (most recent call last):\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/validators/validation_base.py\", line 127, in tearDown\n    self.engine_handler.stop_engine()\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/engine_handler.py\", line 115, in stop_engine\n    if not self.engine_running():\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/engine_handler.py\", line 128, in engine_running\n    self.device.run_command('docker ps')\n  File \"/Users/nacho/PycharmProjects/nuvlaedge/devel/validation/validation_framework/deployer/target_device/ssh_target.py\", line 86, in run_command\n    return connection.run(command, env=envs, hide=True)\n  File \"<decorator-gen-3>\", line 2, in run\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 29, in opens\n    self.open()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/fabric/connection.py\", line 636, in open\n    self.client.connect(**kwargs)\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/client.py\", line 358, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/util.py\", line 279, in retry_on_signal\n    return function()\n  File \"/Users/nacho/Library/Caches/pypoetry/virtualenvs/validation-3EvBwfil-py3.10/lib/python3.10/site-packages/paramiko/client.py\", line 358, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\nTimeoutError: timed out"
                    },
                    "system-out": "~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml\nnohup docker-compose -p NuvlaEdge_Validator -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.bluetooth.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.gpu.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.modbus.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.network.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.security.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.usb.yml -f ~/.nuvlaedge_validation/engines/2.4.3/docker-compose.yml up -d\n{'location': 'job/a0dce27e-ac36-4c95-aa81-86357d09a475',\n 'message': 'sending reboot request to NuvlaBox '\n            'nuvlabox/3a8f2283-8033-4a3c-8b07-ae3168d67ae6 with async '\n            'job/a0dce27e-ac36-4c95-aa81-86357d09a475',\n 'resource-id': 'nuvlabox/3a8f2283-8033-4a3c-8b07-ae3168d67ae6',\n 'status': 202}"
                }
            ]
        }
    },
    "target_device": "rpi4.toml"
}